#!/bin/sh

# be sure that our scripts are publicy available
export PATH=$PATH:$HOME/.config/my-user-configurations/scripts

# be sure thet minecraft can be found
export PATH=$PATH:/opt/minecraft

# make sure that the ruby gems are found
export PATH="$PATH:$(ruby -e 'print Gem.user_dir')/bin"

# fix a bug with awesome and java applications
wmname LG3D

# load the new modified key map
xmodmap ~/.Xmodmap

# ensure that our synergy server is running
# synergys

# start the dropbox deamon
dropbox &

# start the file manager daemon
pcmanfm -d &

# start the SparkleShare client
#sparkleshare start &

# enable the battery icon
cbatticon &

# enable the numlock while logging in
numlockx &

# enable the network-manager applet
nm-applet &

# enable the tool for controlling the snd
volumeicon &

#
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# start conky
# conky &

# enable the taskwarrior webserver
# task-web --port 5678 --host 127.0.0.1 --no-launch

#
source ~/.config/my-user-configurations/shell/shell_paths.notebook
