#!/bin/sh

# fix a bug with awesome and java applications
wmname LG3D

# ensure that our synergy server is running
# synergys

# start the dropbox deamon
dropboxd &

# start the SparkleShare client
#sparkleshare start &

# enable the numlock while logging in
numlockx &

# enable the network-manager applet
nm-applet &

# enable the tool for controlling the snd
volumeicon &

# enable the taskwarrior webserver
# task-web --port 5678 --host 127.0.0.1 --no-launch
