# get the physical path to the file
_PHYSZSH=$(readlink ~/.zshrc)
PHYSPATH=$(dirname $_PHYSZSH)

# path to your oh-my-zsh configuration.
ZSH=$PHYSPATH/../../../oh-my-zsh

# set name of the theme to load.
ZSH_THEME="agnoster"

# which plugins would you like to load?
plugins=(git)

#
export DISABLE_AUTO_TITLE=true

#
source $ZSH/oh-my-zsh.sh

# source some other required scripts
#source /usr/lib/ruby/gems/2.1.0/gems/tmuxinator-0.6.6/completion/tmuxinator.zsh

# fix a bug with java apps and awesome
export _JAVA_AWT_WM_NONREPARENTING=1

# set the default editor which should be used
export EDITOR="vim"

# set the correct umask
umask 002

#
if [[ "$(hostname)" == "zockepeter" ]]; then
	echo "Loaded shell scripts for the computer at home"
	source $PHYSPATH/../shell_paths.zockepeter
elif [[ "$(hostname)" == "imedv18" ]]; then
	echo "Loaded shell scripts for the computer at work"
	source $PHYSPATH/../shell_paths.imedv18
else
	echo "Loaded shell scripts for my notebook"
	source $PHYSPATH/../shell_paths.notebook
fi

# define a list of aliases we want to use in our shell
alias ll="clear && ls -lh"
alias la="clear && ls -lha"
alias pac="yaourt"
alias gits="clear && git status"
alias tigger="tig --all"
alias open="xdg-open"
alias grep="grep -i --color=auto"
alias nb="ipython2 notebook --pylab=inline"
alias dev="terminator -l programming"
alias tlw="clear && task +work long && task calendar"
alias tlp="clear && task +private long && task calendar"
alias tbw="clear && task +work burndown.daily"
alias tbp="clear && task +private burndown.daily"
alias gap="clear && git add -p"
